spring:
  flyway:
    enabled: false
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
  main:
    allow-bean-definition-overriding: true
#  mongodb:
#    embedded:
#      features: SYNC_DELAY
