spring:
  flyway:
    enabled: false
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://docker.for.mac.localhost:27018/spg_friends}
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
  main:
    allow-bean-definition-overriding: true