spring:
  flyway:
    enabled: false
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/spg_friends
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
  main:
    allow-bean-definition-overriding: true
